[build]
  publish = "."
  ignore = "git diff --quiet HEAD^ HEAD -- index.html netlify/ netlify.toml"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
